source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'SSKeychain', '~> 1.2.2'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MKNetworkKit', '~> 0.87'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'FormatterKit', '~> 1.8.0'
pod 'DZNEmptyDataSet', '~> 1.5.1'
pod 'Ono', '~> 1.2.0'
pod 'UMengAnalytics', '~> 3.4.6'
#pod 'Reveal-iOS-SDK', '~> 1.5.1'
pod 'FMDB'

pod 'OcticonsIOS', :git => 'git@github.com:jacksonh/OcticonsIOS.git', :commit => '4bd3b21'
pod 'CBStoreHouseRefreshControl', :git => 'git@github.com:coolbeet/CBStoreHouseRefreshControl.git', :commit => '0bec93d'
